### ISSUE TITLE
Launcher immediately shows crash message instead of starting up WITH THE MOD

### ISSUE THREAD

**Issue by StickyChannel92** [samolego/MobDisguises#13] opened 2021-09-17 04:41 UTC
Launcher immediately shows a crash message, right after clicking on "Play" in the launcher. Without the mod, this is no issue.

**Comment by samolego** [comment] 2021-09-17 04:45
Logs please :)

**Comment by StickyChannel92** [comment] 2021-09-17 16:38
[crash-2021-09-16_23.26.20-client.txt](https://github.com/samolego/MobDisguises/files/7187088/crash-2021-09-16_23.26.20-client.txt)

**Comment by samolego** [comment] 2021-09-17 20:29
Can you try removing `identity` mod?

**Comment by StickyChannel92** [comment] 2021-09-21 10:37
There's no identity, since I just moved to another device. Anyways, leaving it out does not fix the problem.

**Comment by StickyChannel92** [comment] 2021-09-21 10:39
Or is _this_ the log? It's called latest.log, which was done at 5:35am 9/21/2021
[latest.log](https://github.com/samolego/MobDisguises/files/7202447/latest.log)

**Comment by samolego** [comment] 2021-09-21 11:41
> Or is _this_ the log? It's called latest.log, which was done at 5:35am 9/21/2021
> [latest.log](https://github.com/samolego/MobDisguises/files/7202447/latest.log)

This doesn't seem like whole log ...

**Comment by StickyChannel92** [comment] 2021-09-21 15:09
So where would `identity` be? I don't seem to have it anymore. Leaving whatever the identity mod is doesn't work.

**Comment by James103** [comment] 2021-09-21 15:40
> [crash-2021-09-16_23.26.20-client.txt](https://github.com/samolego/MobDisguises/files/7187088/crash-2021-09-16_23.26.20-client.txt)

That crash is a duplicate of https://github.com/Draylar/identity/issues/277.

**Closed** 2022-11-15 15:53 UTC
